language: node_js
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm install -g codecov
node_js:
  - "8"
script:
  - yarn test
  - yarn deploy
after_script:
  - ls -l build/* build.zip
  - sha256sum build/* build.zip | tee SHA256SUMS.txt
  - cat build/* | sha256sum | tee -a SHA256SUMS.txt
  - yarn codecov
  - yarn coveralls
  - yarn lcov && ./cc-test-reporter after-build --coverage-input-type lcov
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - build.zip
    - SHA256SUMS.txt
  skip_cleanup: true
  on:
    tags: true
